<?php
namespace app\applet\controller;

use SimpleXMLElement;

class Index extends Applet
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 微信接口对接    2015-11-16
     */
    public function index()
    {
        //获取接口Token值和UID
        $userModel = M('SystemUser');
        $user = $userModel->where(array('id' => WID))->find();

        $Config = new \Purewechat\Controller\ConfigController($user['token']);;
        $data = $Config->request();

        $openid = $data['FromUserName'];
        define('OPENID', $openid);
        session('openid', $openid);

        list($content, $type) = $this->reply($data);
        $Config->response($content, $type);
    }

    /**
     * 消息回复
     */
    protected function reply($data)
    {
        if ($data['MsgType'] == 'event') {    //事件推送
            if ($data['Event'] == 'user_enter_tempsession') {    //关注事件
                $reply = $this->replytempsession($data['sessionFrom']);
            }
        } else if ($data['MsgType'] == 'text') {    //文本消息
            $reply = $this->replykeywords($data['Content']);
        } else if ($data['MsgType'] == 'image') {
            $reply = $this->replyimage($data['MediaId']);
        } else {
            $reply = array("未知消息类型", 'text');
        }

        return $reply;
    }

    protected function replytempsession($sessionFrom)
    {
        $data = array();
        $data[] = '';
        $data[] = 'transfer_customer_service';
        return $data;
    }

    protected function replykeywords($text)
    {
        //解析关键词
        $data = array();
        $data[] = '';
        $data[] = 'transfer_customer_service';
        return $data;

    }

    public function replyimage()
    {
        $data = array();
        $data[] = '';
        $data[] = 'transfer_customer_service';
        return $data;
    }


    public function generateImg()
    {
        //http://my.oschina.net/cart/


        $textInfo[0] = array(
            'text' => "PHP很多很多很多文字水平居中",
            'color' => array(255, 0, 0),
            'fontsize' => 18,
            'width' => 280,
            'left' => 10,
            'top' => 370,
        );
        $textInfo[1] = array(
            'text' => "￥ 168",
            'color' => array(255, 0, 0),
            'fontsize' => 18,
            'width' => 280,
            'left' => 10,
            'top' => 470,
        );


        $imgInfo=array();

        $result = generateImg('http://192.168.31.248/static/common/images/bg.png',$imgInfo,$textInfo);
//        dump($result);


        echo "<img src='http://192.168.31.248/" . $result . "'>";

        exit ();

    }


}