<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/9
 * Time: 23:37
 */
namespace app\mobile\controller;

use app\common\logic\AgentLogic;
use app\mobile\controller\Wechat;

class Agent extends Base
{
    public  $vid_ids=[];
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $user = session('userinfo');
        $this->vid_ids=session('vip_ids');
        if (empty($user)) {
            $this->error('你还没有登录，请先登录');
        }
    }
    public function index()
    {
        $user = session('userinfo');
        $user = db(\tname::vip)->where(['uid' => WID, 'id' => $user['vip_id']])->find();
        $user['_mobile']=hidtel($user['mobile']);

        $config = tpCache('base');
        $webConfig = tpCache('web');
        $config['logo'] = imgurlToAbsolute($webConfig['logo']);
        $config['slogen'] = $webConfig['slogen'];
        //代理权益
        $article = db(\tname::topic)->find(2);
        $article['content'] = str_replace("<img ", "<img class='img_w' ", $article['content']);

        //代理信息
        $AgentLogic = new AgentLogic();
        $agent = $AgentLogic->agentInfo($user);
        $this->assign('user',$user);
        $this->assign('agent',$agent);
        $this->assign('article',$article);
        $this->assign('config',$config);
        return $this->fetch();
    }
    /**
     * 修改个人资料
     */
    public function userinfo(){
        $user = session('userinfo');
        $user = db(\tname::vip)->where(['id' => $user['vip_id']])->find();
        //代理信息
        $AgentLogic = new AgentLogic();
        $agent = $AgentLogic->agentInfo($user);
        $this->assign('user',$user);
        $this->assign('agent',$agent);
        return $this->fetch();
    }
    /**
     * 执行修改
     */
    public function  editInfo(){
        $pdata = input('post.');
        $user = db(\tname::vip)->where(['id' => $pdata['vip_id']])->find();
        $AgentLogic = new AgentLogic();
        $result = $AgentLogic->editInfo($user,$pdata);
        return json($result);
    }

    /**
     * 代理申请
     */
    public function apply()
    {
        $user = session('userinfo');
        $user = db(\tname::vip)->where(['uid' => WID, 'id' => $user['vip_id']])->find();
        $agent = db(\tname::agent_user)->where(array('mobile' => $user['mobile']))->find();
        $xieyi = db(\tname::topic)->where(array('id' => 1))->find();
        $config = tpCache('base');
        $webConfig = tpCache('web');
        $config['logo'] = imgurlToAbsolute($webConfig['logo']);
        $config['agent_apply_bg'] = imgurlToAbsolute($config['agent_apply_bg']);
        $config['slogen'] = $webConfig['slogen'];
        $this->assign('user',$user);
        $this->assign('agent',$agent);
        $this->assign('xieyi',$xieyi);
        $this->assign('config',$config);
        return $this->fetch();
    }


    /**
     * 代理申请提交
     */
    public function apply_do()
    {
        $user = session('userinfo');
        $pdata = input('post.');
        $AgentLogic = new AgentLogic();
        $result = $AgentLogic->agentApply($user['vip_id'], $pdata);
        return json($result);
    }

    /**
     * 充值页面
     */
    public function recharge()
    {
        $user = session('userinfo');
        $user = db(\tname::vip)->where(['uid' => WID, 'id' => $user['vip_id']])->find();
        $user['_mobile']=hidtel($user['mobile']);
        //代理信息
        $AgentLogic = new AgentLogic();
        $agent = $AgentLogic->agentInfo($user);

        //余额说明
        $article = db(\tname::topic)->find(3);
        $article['content'] = str_replace("<img ", "<img class='img_w' ", $article['content']);
        $moneyList = array(
            array('money' => 100),
            array('money' => 300),
            array('money' => 1500),
            array('money' => 1000),
            array('money' => 3000),
            array('money' => 5000),
        );
        $ajaxdata = [
            'user' => $user,
            'agent' => $agent,
            'article' => $article,
            'money' => $moneyList[0]['money'],
            'moneyList' => $moneyList,
        ];
        $this->assign('user',$user);
        $this->assign('agent',$agent);
        $this->assign('article',$article);
        $this->assign('moneyList',$moneyList);
        return $this->fetch();
    }

    /**
     * 充值下单
     */
    public function orderadd()
    {
        $user = session('userinfo');
        $pdata = input('post.');
        $user = db(\tname::vip)->where(['uid' => WID, 'id' => $user['vip_id']])->find();
        $agent = db(\tname::agent_user)->where(array('mobile' => $user['mobile']))->find();
        if (empty($agent)) {
            return join(ajaxFalse('系统未检测到您的代理信息'));
        }
        $rechargeData = array(
            'agent_id' => $agent['id'],
            'vip_id' => $user['id'],
            'source'=>'mobile',
            'pay_type' => $pdata['pay_type'],
            'order_sn' => createOrdernumber(\tname::agent_recharge, 'order_sn'),
            'pay_money' => $pdata['money'],
            'give_money' => 0,
            'create_time' => time(),
        );
        $res = dataUpdate(\tname::agent_recharge, $rechargeData);
        if (empty($agent)) {
            return join(ajaxFalse('充值失败，请稍后重试'));
        }
        $rechargeData['id'] = $res;
        $AgentLogic = new AgentLogic();
//        $result = $AgentLogic->rechargePay($rechargeData,'mobile');
        $ajaxdata = array(
            'ret' => 1,
            'msg' => "",
            'order' => $rechargeData,
        );
        return json($ajaxdata);
    }
    /**
     * 充值支付
     */
    public function rechargePay(){
        $user = session('userinfo');
        $pdata = input('param.');
        $AgentLogic = new AgentLogic();
        $order =$AgentLogic->getOrderInfo($user['vip_id'],$pdata['order_id']);
        if($order['pay_type']=='alipay'){
            $apipay = new \alipay\Wappay();
            $money = $order['pay_money'];
            $money = 0.01;
            $params=array(
                'out_trade_no'=>$order['order_sn'],
                'subject'=>'晓爱科技',
                'total_amount'=>$money,
                'return_url'=>get_domain().url('Agent/index'),
                'notify_url'=>get_domain().url('Special/indepNotify',array('uid'=>WID,'orderType'=>'recharge')),
            );
            $apipay::pay($params);
        }
    }


    /**
     * 余额记录
     */
    public function balance_log()
    {
        $user = session('userinfo');
        if(request()->isPost()) {
            $pdata = input('post.');
            $pdata['pagenum']=20;
            $AgentLogic = new AgentLogic();
            $dataList = $AgentLogic->getBalanceLog($pdata, $user['vip_id']);
            foreach ($dataList as &$val) {
                $val['_create_time'] = date('Y-m-d H:i:s', $val['create_time']);
            }
            $this->assign('dataList', $dataList);
            $html = $this->fetch('vip/ajaxdata');
            $attach = array(
                'total' => '',
                'page_size' => 20,
                'count' => count($dataList),
            );
            return ajaxSuccess($html, '', '', $attach);
        }
        return $this->fetch();
    }
    /**
     * 充值记录
     */
    public function recharge_log(){
        $user = session('userinfo');
        if(request()->isPost()){
            $pdata = input('post.');
            $pdata['pagenum']=20;
            $AgentLogic = new AgentLogic();
            $dataList = $AgentLogic->getRechargeLog($pdata,$user['vip_id']);
            $statusList= array(
                '0'=>'未成功',
                '1'=>'充值成功',
                '2'=>'充值失败',
            );
            foreach ($dataList as &$val){
                $val['_create_time']=date('Y-m-d H:i:s',$val['create_time']);
            }
            $this->assign('dataList', $dataList);
            $html = $this->fetch('vip/ajaxdata');
            $attach = array(
                'total' => '',
                'page_size' => 20,
                'count' => count($dataList),
            );
            return ajaxSuccess($html, '', '', $attach);
        }
        return $this->fetch();
    }


    /**
     * 处理支付的反馈结果——订单支付完成
     */
    public function indepNotify()
    {
        $uid = input('param.uid');
        $xml = file_get_contents('php://input');
        $data = xmltoarray($xml);
        $pay = db(\tname::weixin_pay)->where(array('uid' => $uid,'type'=>'applet'))->find();
        $wxpayparam = serializeMysql($pay['wxpay'], 1);
        $Wxpay = new \wechat\Wxpay();
        $sign = $Wxpay->checksign($data, $wxpayparam);
        $returnParameters = array();
        if ($sign == false) {
            $returndata = array(
                'return_code' => 'FAIL',
                'return_msg' => '签名失败'
            );
        } else {
            $returndata = array(
                'return_code' => 'SUCCESS',
                'return_msg' => 'OK'
            );
        }
        $xml = new \SimpleXMLElement('<xml></xml>');
        data2xml($xml, $returndata);
        $returnXml = $xml->asXML();
        echo $returnXml;
        apilog($uid, 'applet', 'wxpaynotify-rechange', '', $data, $returndata);
        $order = db(\tname::agent_recharge)->where('order_sn', $data['out_trade_no'])->find();
        $AgentLogic = new AgentLogic();
        $AgentLogic->rechargePaySuccess($order,'wxpay',$data['transaction_id']);
    }









}